### ISSUE TITLE
Where to put "open questions" re Gibson ?

### ISSUE THREAD

**Issue by emdupre** [patrickmineault/big-neuro-ideas#1]
As we've been discussing Gibson's idea of hierarchies (how they structure the world but are interdependent and overlapping), I keep thinking of Kate Crawford's 2017 NeurIPS keynote and how [she points to the problem of classification](https://www.youtube.com/watch?v=fMym_BKWQzk&feature=youtu.be&t=1485): how the structures we identify are always strongly influenced by our current social structure, despite the best efforts of scientists to identify "true" structure for centuries.

This is a general point that sort of aligns with the first week, but also doesn't. Any ideas for where it could go ?

**Comment by patrickmineault** [comment]
I think in a README.md in the gibson folder would work great.
